name: Auto PR Creation

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
      - 'master'
      - 'release/**'

jobs:
  create-draft-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit message and create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Crear PR en estado draft
          PR_NUMBER=$(curl -s -L  \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d @- <<EOF
          {
            "title": "${{ github.ref_name }}",
            "head": "${{ github.ref_name }}",
            "base": "dev",
            "body": "Este PR lo esta creando automaticamente por bot by ${{ github.actor }}.",
            "draft": true
          }
          EOF
          )
          echo "$PR_NUMBER" | jq -r '.number' > pr_number.txt
          echo "pr_number=$(cat pr_number.txt)" >> $GITHUB_ENV