name: Auto PR Creation

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
      - 'master'
      - 'release/**'

jobs:
  create-draft-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit message and create PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
        
          # Obtener el mensaje del último commit
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          echo "Commit message: $COMMIT_MESSAGE"
          
          # Limpiar el mensaje del commit (remover saltos de línea para el título)
          PR_TITLE=$(echo "$COMMIT_MESSAGE" | head -n1 | sed 's/^\[[^]]*\]//' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
          echo "PR Title: $PR_TITLE"

          # Crear PR en estado draft
          PR_NUMBER=$(curl -s -L  \
            -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d @- <<EOF
          {
            "title": "$PR_TITLE",
            "head": "${{ github.ref_name }}",
            "base": "dev",
            "body": "Este PR lo esta creando automaticamente un bot by ${{ github.actor }}.",
            "draft": true
          }
          EOF
          )
          echo "$PR_NUMBER" | jq -r '.number' > pr_number.txt
          echo "pr_number=$(cat pr_number.txt)" >> $GITHUB_ENV