name: Auto PR Creation

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  create-draft-pr:
    runs-on: ubuntu-latest
    concurrency: auto-pr-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set branch name
        run: |
          # Extraer solo el nombre de la branch sin 'refs/heads/'
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          PR_RESPONSE=$(curl -s -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/pulls" \
            -d "{
              \"title\": \"Auto PR: ${{ env.BRANCH_NAME }}\",
              \"head\": \"${{ env.BRANCH_NAME }}\",
              \"base\": \"dev\",
              \"body\": \"Este PR fue creado automáticamente por el bot.\\n\\n**Branch:** ${{ env.BRANCH_NAME }}\\n**Creado por:** ${{ github.actor }}\\n**Fecha:** $(date)\",
              \"draft\": true
            }")

          # Verificar si la creación fue exitosa
          if echo "$PR_RESPONSE" | jq -e '.number' > /dev/null 2>&1; then
            PR_NUMBER=$(echo "$PR_RESPONSE" | jq -r '.number')
            echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
            echo "PR creado exitosamente: #$PR_NUMBER"
            
            # Guardar el número para pasos siguientes
            echo "$PR_NUMBER" > pr_number.txt
          else
            echo "Error creando PR:"
            echo "$PR_RESPONSE"
            exit 1
          fi

      # - name: Add Labels to PR
      #   if: env.PR_NUMBER != ''
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     curl -s -L \
      #       -X POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Authorization: Bearer $GITHUB_TOKEN" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       "https://api.github.com/repos/${{ github.repository }}/issues/${{ env.PR_NUMBER }}/labels" \
      #       -d '{\"labels\":[\"auto-generated\",\"bot\"]}'

      # - name: Show PR Info
      #   if: env.PR_NUMBER != ''
      #   run: |
      #     echo "✅ PR creado exitosamente:"
      #     echo "Número: ${{ env.PR_NUMBER }}"
      #     echo "URL: https://github.com/${{ github.repository }}/pull/${{ env.PR_NUMBER }}"